// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArgA0cEvwa3O0FaSclOj17nH3ELAr5HB0',
    appId: '1:1097729806831:web:73f479204890c00fb2a61a',
    messagingSenderId: '1097729806831',
    projectId: 'eleytra-auth',
    authDomain: 'eleytra-auth.firebaseapp.com',
    storageBucket: 'eleytra-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQe2OkXYNMl9Z4tchSiNAssrzTWleSSOY',
    appId: '1:1097729806831:android:a67fe8777a5c3d71b2a61a',
    messagingSenderId: '1097729806831',
    projectId: 'eleytra-auth',
    storageBucket: 'eleytra-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCldwmk55JMZMASsmcGtc2Uf6D-YPB5dXE',
    appId: '1:1097729806831:ios:3f362a6e615f5968b2a61a',
    messagingSenderId: '1097729806831',
    projectId: 'eleytra-auth',
    storageBucket: 'eleytra-auth.appspot.com',
    iosBundleId: 'com.example.eleytra',
  );
}
